kafka_broker_service_environment_overrides:
  JMX_PORT: 9999
  KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote.rmi.port=9999 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname={{inventory_hostname}} -Dcom.sun.management.jmxremote.local.only=false"
kafka_broker_sysctl:
  vm.swappiness: 1
  net.core.rmem_max: '{{tuned_buffer_size}}'
  net.core.wmem_max: '{{tuned_buffer_size}}'
  net.ipv4.tcp_mem: '{{tuned_buffer_size}} {{tuned_buffer_size}} {{tuned_buffer_size}}'
  net.ipv4.tcp_rmem: '4096 87380 {{tuned_buffer_size}}'
  net.ipv4.tcp_wmem: '4096 212992 {{tuned_buffer_size}}'
kafka_broker:  
  properties:
    advertised.listeners: "INTERNAL://{{inventory_hostname}}:9091,EXTERNAL://{{inventory_hostname}}:9093"
    authorizer.class.name: "kafka.security.auth.SimpleAclAuthorizer"
    super.users: "User:kafka1.ivan.confluent.nerdynick.net;User:kafka2.ivan.confluent.nerdynick.net;User:kafka3.ivan.confluent.nerdynick.net"
    ssl.principal.mapping.rules: |
                                      RULE:^CN=(.*?),OU=.*?,O=.*?,L=.*?,ST=.*?,C=.*?$/$1/, \
                                      RULE:^CN=(.*?)$/$1/L, \
                                      DEFAULT
    socket.receive.buffer.bytes: "{{tuned_buffer_size}}"
    socket.send.buffer.bytes: "{{tuned_buffer_size}}"
