---
- name: debian apt-get update
  shell: apt-get -o Acquire::Check-Valid-Until=false update
  args:
    warn: no

- name: apt-get update
  shell: apt-get update
  args:
    warn: no

- name: yum-clean-all
  command: yum clean all
  args:
    warn: no

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart kerberos redhat
  systemd:
    name: "{{ item }}"
    state: restarted
  loop: "{{kerberos_services_redhat}}"

- name: restart kerberos ubuntu
  systemd:
    name: "{{ item }}"
    state: restarted
  loop: "{{kerberos_services_ubuntu}}"
