---
- name: Remove CP installation
  gather_facts: no 
  become: true
  hosts: all
  ignore_errors: True
  vars:
    installation_method: archive
    confluent_repo_version: 7.6
    confluent_package_version: 7.6.1
    archive_destination_path: /opt/confluent
    confluent_full_package_version: "{{ confluent_package_version + '-1' }}"
    confluent_package_redhat_suffix: "{{ '-' + confluent_full_package_version if confluent_full_package_version != '' else ''}}"
    confluent_package_debian_suffix: "{{ '=' + confluent_full_package_version if confluent_full_package_version != '' else ''}}"
    all_packages:
      - java-11-openjdk
      - java-17-openjdk
      - java-1.8.0-openjdk
      - openjdk-8-jdk
      - confluent-common
      - confluent-rest-utils
      - confluent-metadata-service
      - confluent-ce-kafka-http-server
      - confluent-kafka-rest
      - confluent-server-rest
      - confluent-telemetry
      - confluent-server
      - confluent-rebalancer
      - confluent-security    
      - confluent-kafka
      - confluent-control-center-fe
      - confluent-control-center   
      - confluent-ksqldb
      - confluent-ksql 
      - confluent-schema-registry
      - confluent-hub-client
      - confluent-kafka-connect-replicator    
      - confluent-kafka-2.12
      - confluent-kafka-2.11
      - confluent-kafka
    cp_group: confluent
    all_users:
      - cp-metadata-service
      - cp-ce-kafka-http-server
      - cp-kafka-rest
      - cp-ce-kafka-rest
      - cp-kafka
      - cp-kafka-connect
      - cp-control-center
      - cp-schema-registry
      - cp-ksql
    all_component_services:
      - confluent-control-center
      - confluent-kafka-connect
      - confluent-kafka-rest
      - confluent-ksqldb
      - confluent-ksql
      - confluent-schema-registry
    all_services:
      - confluent-control-center
      - confluent-kafka-connect
      - confluent-kafka-rest
      - confluent-kafka
      - confluent-kcontroller
      - confluent-server
      - confluent-zookeeper
      - confluent-ksqldb
      - confluent-ksql
      - confluent-schema-registry
    all_data:
      - controller
      - kafka
      - confluent
      - kafka-streams
      - zookeeper
    all_config:
      - kafka
      - controller
      - schema-registry
      - kafka-rest
      - zookeeper
      - ksqldb
      - confluent-control-center
      - confluent-metadata-service
      - confluent-rebalancer
    all_roles:
      - zookeeper
      - kafka_controller
      - kafka_broker
      - kafka_connect
      - kafka_connect_replicator
      - kafka_rest
      - ksql
      - control_center
      - schema_registry
    all_else:
      - /usr/local/bin/confluent
      - /opt/prometheus
      - /opt/jolokia
      - "{{ archive_destination_path }}"
      - /var/log/kafka
      - /var/log/controller
      - /var/log/confluent
      - /var/log/kafka-connect



  tasks:
  - name: Gather OS Facts
    setup:
      # Only gathers items in list, filters out the rest
      filter: "{{item}}"
      gather_subset:
        - '!all'
    loop:
      - ansible_os_family
      - ansible_fqdn  

  - set_fact:
      controller_group: "{{ groups['zookeeper'] if 'zookeeper' in groups else groups['kafka_controller'] }}"

  - set_fact:
      component_list: "{{ groups['schema_registry']|d([]) + groups['control_center']|d([]) + groups['kafka_connect']|d([]) + groups['kafka_connect_replicator']|d([]) + groups['kafka_rest']|d([]) + groups['ksql']|d([]) + groups['ksqldb']|d([]) }}"

  - name: Recursively stop component services
    ansible.builtin.systemd:
      name: "{{ item }}"
      state: stopped
    loop: "{{ all_component_services }}"
    when: inventory_hostname in component_list

  - name: Recursively stop broker services
    ansible.builtin.systemd:
      name: confluent-server
      state: stopped
    when: inventory_hostname in groups['kafka_broker']

  - name: Recursively stop controller services
    ansible.builtin.systemd:
      name: confluent-kcontroller
      state: stopped
    when: inventory_hostname in controller_group

  - name: Recursively stop controller services
    ansible.builtin.systemd:
      name: confluent-zookeeper
      state: stopped
    when: inventory_hostname in controller_group

  - name: Uninstall the packages
    yum:
      name: "{{item}}{{confluent_package_redhat_suffix}}"
      state: absent
    loop: "{{ all_packages }}"
    when:
      - ansible_os_family == "RedHat"
      - installation_method == "package"
    tags: package

  - name: Unnstall the packages
    apt:
      name: "{{item}}{{confluent_package_debian_suffix}}"
      state: absent
    loop: "{{ all_packages }}"
    when:
      - ansible_os_family == "Debian"
      - installation_method == "package"
    tags: package
 
  - name: Remove Users
    user:
      name: "{{item}}"
      state: absent
      group: "{cp_group}}"      
    loop: "{{all_users}}"

  # Configure environment
  - name: Remove Group
    group:
      state: absent
      name: "{{cp_group}}"

  - name: Recursively remove service override
    ansible.builtin.file:
      path: /usr/lib/systemd/system/{{ item }}.service
      state: absent
    loop: "{{ all_services }}"

  - name: Recursively remove override directory
    ansible.builtin.file:
      path: /etc/systemd/system/{{ item }}.service.d
      state: absent
    loop: "{{ all_services }}"

  - name: Recursively remove file folders
    ansible.builtin.file:
      path: /var/lib/{{ item }}
      state: absent
    loop: "{{ all_data }}"

  - name: Remove certs
    ansible.builtin.file:
      path: /var/ssl/private
      state: absent

  - name: Recursively remove config
    ansible.builtin.file:
      path: /etc/{{ item }}
      state: absent
    loop: "{{ all_config }}"
    when:
      - installation_method == "package"

  - name: Recursively remove keytabs
    ansible.builtin.file:
      path: /etc/security/keytabs/{{ item }}.keytab
      state: absent
    loop: "{{ all_roles }}"

  - name: Recursively remove all else
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    loop: "{{ all_else }}"

  - name: Just force systemd to reread configs 
    ansible.builtin.systemd:
      daemon_reload: yes    
