---
- name: Kernel changes
  hosts: zookeeper:kafka_broker:schema_registry:kafka_connect:ksql:control_center:kafka_rest
  become: true
  gather_facts: false
  vars:
     sysctl_config:
       vm.swappiness: 1
       net.core.rmem_max: '{{tuned_buffer_size}}'
       net.core.wmem_max: '{{tuned_buffer_size}}'
       net.ipv4.tcp_mem: '{{tuned_buffer_size}} {{tuned_buffer_size}} {{tuned_buffer_size}}'
       net.ipv4.tcp_rmem: '4096 87380 {{tuned_buffer_size}}'
       net.ipv4.tcp_wmem: '4096 212992 {{tuned_buffer_size}}'
       
  
  tasks:
  - name: Change kernel settings
    sysctl:
      name: '{{ item.key }}'
      value: '{{ item.value }}'
      state: present
    with_dict: '{{ sysctl_config }}'
#  - name: net.core.rmem_max
#    sysctl:
#      name: net.core.rmem_max
#      value: "{{tuned_buffer_size}}"
#      state: present
#  - name: net.core.wmem_max
#    sysctl:
#      name: net.core.wmem_max
#      value: '{{tuned_buffer_size}}'
#      state: present
#  - name: net.ipv4.tcp_mem
#    sysctl:
#      name: net.ipv4.tcp_mem
#      value: '{{tuned_buffer_size}} {{tuned_buffer_size}} {{tuned_buffer_size}}'
#      state: present
#  - name: net.ipv4.tcp_rmem
#    sysctl:
#      name: net.ipv4.tcp_rmem
#      value: '4096 87380 {{tuned_buffer_size}}'
#      state: present
#  - name: net.ipv4.tcp_wmem
#    sysctl:
#      name: net.ipv4.tcp_wmem
#      value: '4096 212992 {{tuned_buffer_size}}'
##      state: present
  - name: net.ipv4.route.flush
    sysctl:
      name: net.ipv4.troute.flush
      value: '1'
      state: absent
